# Generated by Django 5.1.6 on 2025-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_going',
            field=models.BooleanField(default=True),
        ),
    ]
