# Generated by Django 5.1.6 on 2025-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='generos',
            field=models.TextField(default=''),
        ),
    ]
