# Generated by Django 5.1.6 on 2025-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_item_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
