# Generated by Django 5.1.6 on 2025-03-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(default='', max_length=6),
        ),
    ]
